### ISSUE TITLE
how to run ?

### ISSUE THREAD

**Issue by mr-woot** [JostineHo/mememoji_api#1]
how to run the flask app, add atleast steps to install the dependencies.

**Comment by mr-woot** [comment]
Tushar:webapp mr-woot$ python app.py 
Traceback (most recent call last):
  File "app.py", line 41, in <module>
    import error
  File "/Users/mr-woot/Downloads/mememoji_api-master/webapp/error.py", line 1, in <module>
    from app import app
  File "/Users/mr-woot/Downloads/mememoji_api-master/webapp/app.py", line 42, in <module>
    import admin
  File "/Users/mr-woot/Downloads/mememoji_api-master/webapp/admin.py", line 5, in <module>
    from error import Error
ImportError: cannot import name Error
